# Generated by Django 3.1.7 on 2021-06-03 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_items', '0002_auto_20210603_1451'),
        ('store_item_stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitemstock',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_item_stock', to='store_items.storeitem'),
        ),
    ]
