# Generated by Django 3.1.7 on 2021-06-03 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_item_suppliers', '0001_initial'),
        ('store_item_purchases', '0002_auto_20210603_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitempurchase',
            name='item_supplier',
        ),
        migrations.AddField(
            model_name='storeitempurchasestock',
            name='item_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_item_suppliers.storeitemsupplier'),
        ),
    ]
