# Generated by Django 3.1.7 on 2021-06-03 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_item_stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItemUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('take_out_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Item uses',
                'verbose_name_plural': 'Item uses',
            },
        ),
        migrations.CreateModel(
            name='StoreItemUseStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('is_move_from_stock', models.BooleanField(default=False)),
                ('item_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_item_use_stock', to='store_item_stocks.storeitemstock')),
                ('item_use', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_item_uses.storeitemuse')),
            ],
            options={
                'verbose_name': 'Store Item use Stocks',
                'verbose_name_plural': 'Store Item use Stocks',
            },
        ),
    ]
