# Generated by Django 3.1.7 on 2021-06-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_item_uses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeitemuse',
            options={'verbose_name': 'Store Item uses', 'verbose_name_plural': 'Store Item uses'},
        ),
    ]
