# Generated by Django 3.1.7 on 2021-06-03 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitemimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_item_image', to='store_items.storeitem'),
        ),
    ]
